name: Rust

on:
  release:
    types: [created]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: bash scripts/linux.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stig-view
          path: stig-view.flatpak
  # build-macos:
  #   runs-on: macos-latest
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build
  #       run: cargo build --release -p stig-view-desktop
  #
  #     - name: Upload
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: stig-view-macos
  #         path: target/release/stig_view_desktop
  # build-windows:
  #   runs-on: windows-latest
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build
  #       run: cargo build --release -p stig-view-desktop
  #
  #     - name: Upload
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: stig-view-windows
  #         path: target/release/stig_view_desktop.exe
