name: Rust

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder
          flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak install --user -y flathub org.freedesktop.Platform//25.08 org.freedesktop.Sdk//25.08
      - name: Build
        run: bash scripts/linux.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stig-view
          path: stig-view.flatpak
  # build-macos:
  #   runs-on: macos-latest
  #
  #   steps:
  #     - uses: actions/checkout@v4
  #     - name: Build
  #       run: cargo build --release -p stig-view-desktop
  #
  #     - name: Upload
  #       uses: actions/upload-artifact@v4
  #       with:
  #         name: stig-view-macos
  #         path: target/release/stig_view_desktop
  build-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Cache cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            ~/.cargo/bin
            target
          key: windows-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install cargo-wix
        run: cargo install cargo-wix

      - name: Build
        shell: bash
        run: bash scripts/windows.sh

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: stig-view-windows
          path: target/wix/*.msi
